version: '2'
 
services:
  wordpress:
    image: wordpress
    ports:
      - 8100:80
    environment:
      WORDPRESS_DB_PASSWORD: kiscica
    volumes:
      - .:/var/www/html
      - ./log:/var/log/apache2/
 
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kiscica    
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8101:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: kiscica
 
  wpcli: 
    image: tatemz/wp-cli
    volumes_from:
        - wordpress
    links:
        - mysql:mysql
    entrypoint: wp
    command: "--info"